
import { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('appLanguage') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('appLanguage', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const translations = {
    en: {
      appName: "Islamic Life",
      dashboard: "Dashboard",
      quran: "Quran",
      hadith: "Hadith",
      prayerTimes: "Prayer Times",
      tasbih: "Tasbih",
      dua: "Dua",
      about: "About",
      settings: "Settings",
      home: "Home",
      search: "Search",
      copy: "Copy",
      useMyLocation: "Use My Location",
      locationAccessError: "Unable to access your location.",
      geolocationNotSupported: "Geolocation is not supported by your browser.",
      prayers: "Prayers",
      offline: "Offline",
      online: "Online",
      loading: "Loading...",
      // Dashboard
      appDescription: "Your daily companion for reading Quran, exploring Hadith, and keeping track of prayer times.",
      quranDesc: "Read the Holy Quran with translation and transliteration.",
      hadithDesc: "Explore authentic Hadith from Bukhari, Muslim, and others.",
      prayerTimesDesc: "Accurate prayer times based on your location.",
      tasbihDesc: "Digital rosary for your daily dhikr and remembrances.",
      duaDesc: "Comprehensive collection of authentic Duas for all occasions.",
      verseOfTheMoment: "Verse of the Moment",
      todaysPrayer: "Today's Prayers",
      nextPrayer: "Next Prayer",
      dailyTracker: "Daily Tracker",
      quranProgress: "Quran Progress",
      // Salah Tracker
      fajr: "Fajr",
      dhuhr: "Dhuhr",
      asr: "Asr",
      maghrib: "Maghrib",
      isha: "Isha",
      duha: "Duha",
      tahajjud: "Tahajjud",
      completed: "Completed",
      markAsDone: "Mark as Done",
      tasbihCompleted: "Tasbih Completed",
      wellDone: "MashaAllah! Well done.",
      // Quran
      surah: "Surah",
      ayah: "Ayah",
      ayahs: "Ayahs",
      read: "Read",
      listen: "Listen",
      searchSurah: "Search Surah...",
      fridayChallenge: "Friday Challenge: Read Surah Al-Kahf",
      dailyGoal: "Daily Reading Goal",
      setGoal: "Set Goal",
      pagesPerDay: "Pages per day",
      finishIn: "Finish in",
      days: "days",
      // Tasbih
      tasbihCounter: "Tasbih Counter",
      reset: "Reset",
      target: "Target",
      presets: "Presets",
      custom: "Custom",
      morningAdhkar: "Morning Adhkar",
      eveningAdhkar: "Evening Adhkar",
      afterSalah: "After Salah",
      salah: "Salah",
      common: "Common",
      // Common
      back: "Back",
      save: "Save",
      cancel: "Cancel",
      language: "Language",
      english: "English",
      arabic: "العربية",
      backToSurahs: "Back to Surahs",
      playRecitation: "Play Recitation",
      pauseRecitation: "Pause Recitation",
      audioOffline: "Audio Offline",
      surahNotFound: "Surah not found",
      page: "Page",
      juz: "Juz",
      hizb: "Hizb",
      ruku: "Ruku",
      sajda: "Sajda",
      manzil: "Manzil",
      
      // Reading Mode
      readingMode: "Reading Mode",
      standardMode: "Standard Mode",
      readingSettings: "Reading Settings",
      fontSize: "Font Size",
      openTasbih: "Open Tasbih",
      sunnah: "Sunnah",
      autoTracking: "Auto-Tracking",
      digitalRosary: "Digital Rosary",
      pageCompleted: "Page Completed",
      markAsRead: "Mark as Read",
      currentPage: "Current Page",
      
      // Reading Goals
      quranGoals: "Reading Goals",
      dailyTarget: "Daily Target",
      pages: "Pages",
      surahAlKahf: "Surah Al-Kahf",
      surahAlMulk: "Surah Al-Mulk",
      fridaySunnah: "Friday Sunnah",
      nightlySunnah: "Nightly Sunnah",
      markRead: "Mark Read",
      currentStreak: "Current Streak",
      totalRead: "Total Read",
      searchHadith: "Search Hadith...",
      noHadithsFound: "No hadiths found for your search.",
      specialEvents: "Special Events & Challenges",
      afterSalahAdhkar: "After Salah Adhkar",
      afterSalahDesc: "Keep your post-prayer dhikr and tasbih consistent after the obligatory prayer.",
      fridayKahfChallenge: "Friday Sunnah: Read Surah Al-Kahf",
      surahAlKahfDesc: "It is Sunnah to read Surah Al-Kahf on Fridays.",
      mondaySunnah: "Monday Sunnah: Fasting",
      thursdaySunnah: "Thursday Sunnah: Fasting",
      fastingSunnahDesc: "Fasting on Mondays and Thursdays is a recommended Sunnah.",
      surahAlMulkDesc: "It is recommended to read Surah Al-Mulk every night.",
      morningAdhkarDesc: "Start your day with the remembrance of Allah.",
      eveningAdhkarDesc: "Protect yourself with evening remembrance.",
      tahajjudPrayer: "Tahajjud Prayer",
      tahajjudDesc: "The night prayer is a special time for Dua.",
      duhaPrayer: "Duha Prayer",
      duhaDesc: "The prayer of the repentant (Salat al-Awwabin).",
      witrPrayer: "Witr Prayer",
      witrDesc: "End your night with Witr after Isha and before Fajr.",
      fridaySustenance: "Friday Sunnah: Salawat",
      fridaySustenanceDesc: "Increase your Salawat upon the Prophet (PBUH) on Friday.",
      readAgain: "Read Again",
      challengeAccepted: "Challenge Accepted",
      challengeCompleted: "Challenge Completed!",
      missionComplete: "Mission Complete!",
      challengeCompletedDesc: "MashaAllah! You have completed this reading challenge.",
      backToHome: "Back to Home",
      mashaAllah: "MashaAllah!",
      keepItUp: "Keep it up!",
      startReading: "Start Reading",
      continueReading: "Continue Reading",
      resumeYourLastSession: "Resume your last reading session",
      openReadingMode: "Open Reading Mode",
      enterReadingMode: "Enter Reading Mode",
      exploreTheHolyBook: "Explore the Holy Quran",
      loadingSurahs: "Loading Surahs...",
      gotoAdhkar: "Go to Adhkar",
      adhkar: "Adhkar",
      myPlan: "My Plan",
      startRoutine: "Start Routine",
      noItemsInPlan: "No items in your plan. Click + on any dhikr to add it.",
      rewardsToday: "Rewards Today",
      hasanatEarned: "Hasanat Earned",
      totalLifeTime: "Total Life-time",
      dailyStreak: "Daily Streak",
      startYourJourney: "Start your journey",
      streakUsed: "Streak saved!",
      prayerConfirmed: "Prayer confirmed! Time for Adhkar?",
      // Prayer Times
      sunrise: "Sunrise",
      imsak: "Imsak",
      midnight: "Midnight",
      firstthird: "First Third",
      lastthird: "Last Third",
      city: "City",
      country: "Country",
      locationSecurityError: "Location requires a secure connection (HTTPS). Please enter city manually.",
      noResults: "No results found",
      offlineMode: "Offline Mode",
      selectAdhan: "Select Adhan Voice",
      selectedAdhanVoice: "Adhan Voice",
      optimizePrayerAlerts: "Optimize Prayer Alerts",
      enableExactPrayerAlerts: "Enable Exact Prayer Alerts",
      exactAlarmEnabled: "Exact prayer-time alerts are enabled on this device.",
      exactAlarmNeedsAttention: "Enable exact alarms on Android so prayer notifications fire on time.",
      makkah: "Makkah",
      madinah: "Madinah",
      alaqsa: "Al-Aqsa",
      egypt: "Egypt",
      mishary: "Mishary Al-Afasy",
      testAdhanNotification: "Test Adhan Notification",
      next: "Next",
      finish: "Finish",
      completedPrayerAdhkar: "You have completed this prayer's adhkar.",
      allRightsReserved: "All rights reserved.",
      disclaimer: "Data sources and disclaimer",
      hijriDate: "Hijri",
      ramadan: "Ramadan",
      ramadanDesc: "Ramadan follows the Hijri calendar, so its dates move each year in the Gregorian calendar.",
      lastTenNights: "Last Ten Nights of Ramadan",
      lastTenNightsDesc: "These nights are a special time for prayer, Quran, and seeking Laylat al-Qadr.",
      eidAlFitr: "Eid al-Fitr",
      eidAlFitrDesc: "Celebrate Eid with gratitude, prayer, and strengthening family ties.",
      firstTenDhulHijjah: "First Ten Days of Dhul Hijjah",
      firstTenDhulHijjahDesc: "These are among the most beloved days for worship, dhikr, and righteous deeds.",
      dayOfArafah: "Day of Arafah",
      dayOfArafahDesc: "A blessed day for dua and fasting for those not performing Hajj.",
      eidAlAdha: "Eid al-Adha",
      eidAlAdhaDesc: "A day of Eid prayer, gratitude, sacrifice, and family bonds.",
      islamicNewYear: "Islamic New Year",
      islamicNewYearDesc: "The Hijri year begins today, and its date shifts each year against the Gregorian calendar.",
      dayOfAshura: "Day of Ashura",
      dayOfAshuraDesc: "A blessed day in Muharram, often observed with fasting and gratitude.",
      whiteDaysFasting: "White Days Fasting",
      whiteDaysFastingDesc: "The 13th, 14th, and 15th of the Hijri month are special fasting days.",
      tasuaFast: "Tasu'a Fast",
      tasuaFastDesc: "Fasting the 9th of Muharram pairs with Ashura and follows the Sunnah.",
      ramadanFastToday: "Ramadan Fast Today",
      ramadanFastTodayDesc: "Track your daily fast across Ramadan so the whole month stays connected to the Hijri calendar.",
      ramadanKhatam: "Ramadan Quran Khatam",
      ramadanKhatamDesc: "Work toward completing the entire Quran during Ramadan with automatic page progress.",
      sixOfShawwal: "Six Fasts of Shawwal",
      sixOfShawwalDesc: "Track the six recommended fasts in Shawwal after Eid al-Fitr.",
    },
    ar: {
      appName: "حياة المسلم",
      dashboard: "الرئيسية",
      quran: "القرآن الكريم",
      hadith: "الحديث الشريف",
      prayerTimes: "مواقيت الصلاة",
      tasbih: "المسبحة",
      about: "حول التطبيق",
      settings: "الإعدادات",
      home: "الرئيسية",
      prayers: "الصلاوات",
      offline: "غير متصل",
      online: "متصل",
      loading: "جاري التحميل...",
      // Dashboard
      appDescription: "رفيقك اليومي لقراءة القرآن، واستكشاف الحديث، ومتابعة أوقات الصلاة.",
      quranDesc: "اقرأ القرآن الكريم مع الترجمة والنسخ الصوتي.",
      hadithDesc: "استكشف الأحاديث الصحيحة من البخاري ومسلم وغيرهم.",
      prayerTimesDesc: "أوقات الصلاة دقيقة بناءً على موقعك.",
      tasbihDesc: "مسبحة رقمية لأذكارك اليومية.",
      verseOfTheMoment: "آية اللحظة",
      todaysPrayer: "صلاوات اليوم",
      nextPrayer: "الصلاة القادمة",
      dailyTracker: "المتابعة اليومية",
      quranProgress: "تقدم ختم القرآن",
      // Reading Mode
      readingMode: "وضع القراءة",
      standardMode: "الوضع العادي",
      readingSettings: "إعدادات القراءة",
      fontSize: "حجم الخط",
      openTasbih: "فتح المسبحة",
      sunnah: "سنة",
      autoTracking: "تتبع تلقائي",
      digitalRosary: "مسبحة رقمية",
      pageCompleted: "اكتملت الصفحة",
      markAsRead: "تحديد كمقروء",
      currentPage: "الصفحة الحالية",
      // Salah Tracker
      fajr: "الفجر",
      dhuhr: "الظهر",
      asr: "العصر",
      maghrib: "المغرب",
      isha: "العشاء",
      duha: "الضحى",
      tahajjud: "التهجد",
      completed: "مكتملة",
      markAsDone: "تحديد كمكتملة",
      tasbihCompleted: "تم إكمال التسبيح",
      wellDone: "ما شاء الله! أحسنت.",
      // Quran
      surah: "سورة",
      ayah: "آية",
      ayahs: "آيات",
      juz: "جزء",
      page: "صفحة",
      read: "قراءة",
      listen: "استماع",
      searchSurah: "بحث عن سورة...",
      fridayChallenge: "تحدي الجمعة: قراءة سورة الكهف",
      dailyGoal: "هدف القراءة اليومي",
      setGoal: "تحديد الهدف",
      pagesPerDay: "صفحة يومياً",
      finishIn: "الختم في",
      days: "أيام",
      // Tasbih
      tasbihCounter: "المسبحة الإلكترونية",
      reset: "تصفير",
      target: "الهدف",
      presets: "أذكار مختارة",
      custom: "مخصص",
      morningAdhkar: "أذكار الصباح",
      eveningAdhkar: "أذكار المساء",
      afterSalah: "أذكار بعد الصلاة",
      // Dua
      dua: "الأدعية والأذكار",
      search: "بحث...",
      copy: "نسخ",
      copied: "تم النسخ!",
      share: "مشاركة",
      // Common
      back: "عودة",
      save: "حفظ",
      cancel: "إلغاء",
      language: "اللغة",
      english: "English",
      arabic: "العربية",
      // Reading Goals
      quranGoals: "أهداف القراءة",
      dailyTarget: "الهدف اليومي",
      pages: "صفحات",
      surahAlKahf: "سورة الكهف",
      surahAlMulk: "سورة الملك",
      fridaySunnah: "سنة الجمعة",
      nightlySunnah: "سنة النوم",
      markRead: "تحديد كمقروء",
      currentStreak: "التتابع الحالي",
      totalRead: "مجموع القراءة",
      setYourGoal: "حدد هدفك",
      juzAmma: "جزء عم",
      juzTabarak: "جزء تبارك",
      customSurah: "سورة مخصصة",
      startReading: "ابدأ القراءة",
      continueReading: "تابع القراءة",
      resumeYourLastSession: "أكمل من حيث توقفت",
      openReadingMode: "فتح وضع القراءة",
      enterReadingMode: "دخول وضع القراءة",
      exploreTheHolyBook: "استكشف القرآن الكريم",
      loadingSurahs: "جاري تحميل السور...",
      challengeAccepted: "قبلت التحدي",
      afterSalahAdhkar: "أذكار بعد الصلاة",
      afterSalahDesc: "حافظ على التسبيح والذكر بعد الصلاة المفروضة.",
      mondaySunnah: "سنة الاثنين: الصيام",
      thursdaySunnah: "سنة الخميس: الصيام",
      fastingSunnahDesc: "صيام الاثنين والخميس من السنن المستحبة.",
      surahAlMulkDesc: "يستحب قراءة سورة الملك كل ليلة قبل النوم.",
      morningAdhkarDesc: "ابدأ يومك بذكر الله وحفظه.",
      eveningAdhkarDesc: "حصن نفسك بأذكار المساء.",
      tahajjudPrayer: "صلاة التهجد",
      tahajjudDesc: "قيام الليل وقت مبارك للدعاء والاستغفار.",
      duhaPrayer: "صلاة الضحى",
      duhaDesc: "صلاة الأوابين ووقتها بعد الشروق.",
      witrPrayer: "صلاة الوتر",
      witrDesc: "اختم ليلتك بالوتر بعد العشاء وقبل الفجر.",
      fridaySustenance: "سنة الجمعة: الصلاة على النبي",
      fridaySustenanceDesc: "أكثروا من الصلاة على النبي ﷺ يوم الجمعة.",
      readAgain: "اقرأ مجدداً",
      challengeCompleted: "أتممت التحدي!",
      missionComplete: "تمت المهمة بنجاح!",
      challengeCompletedDesc: "ما شاء الله! لقد أتممت تحدي القراءة بنجاح.",
      backToHome: "العودة للرئيسية",
      mashaAllah: "ما شاء الله!",
      keepItUp: "استمر في هذا العمل!",
      gotoAdhkar: "الذهاب للأذكار",
      adhkar: "الأذكار",
      rewardsToday: "ثواب اليوم",
      hasanatEarned: "حسنات مكتسبة",
      totalLifeTime: "الإجمالي الكلي",
      dailyStreak: "التتابع اليومي",
      startYourJourney: "ابدأ رحلتك",
      streakUsed: "تم استرجاع التتابع!",
      prayerConfirmed: "تم تأكيد الصلاة! وقت الأذكار؟",
      plan: "الخطة",
      finishQuranIn: "ختم القرآن في",
      days30: "30 يوماً",
      days60: "60 يوماً",
      
      allRightsReserved: "جميع الحقوق محفوظة.",
      disclaimer: "مصادر البيانات وإخلاء المسؤولية",
      customDays: "أيام مخصصة",
      
      // Additional Missing Keys
      city: "المدينة",
      country: "الدولة",
      networkError: "خطأ في الشبكة. يرجى المحاولة مرة أخرى.",
      locationError: "لا يمكن العثور على مواقيت الصلاة لهذا الموقع.",
      locationAccessError: "تم رفض الوصول إلى الموقع.",
      locationSecurityError: "الوصول للموقع يتطلب اتصالاً آمناً (HTTPS). يرجى إدخال المدينة يدوياً.",
      sunrise: "الشروق",
      noResults: "لا توجد نتائج",
      offlineMode: "وضع بدون اتصال",
      selectAdhan: "اختر صوت الأذان",
      selectedAdhanVoice: "صوت الأذان",
      optimizePrayerAlerts: "ضبط تنبيهات الصلاة",
      enableExactPrayerAlerts: "تفعيل التنبيهات الدقيقة",
      exactAlarmEnabled: "تنبيهات مواقيت الصلاة الدقيقة مفعلة على هذا الجهاز.",
      exactAlarmNeedsAttention: "فعّل التنبيهات الدقيقة في أندرويد حتى تصل تنبيهات الصلاة في وقتها.",
      makkah: "مكة المكرمة",
      madinah: "المدينة المنورة",
      alaqsa: "المسجد الأقصى",
      egypt: "مصر",
      mishary: "مشاري العفاسي",
      testAdhanNotification: "تجربة إشعار الأذان",
      midnight: "منتصف الليل",
      imsak: "الإمساك",
      firstthird: "الثلث الأول",
      lastthird: "الثلث الأخير",
      revelationType: "مكان النزول",
      meccan: "مكية",
      medinan: "مدنية",

      // Hadith
      by: "بواسطة",
      searchHadith: "بحث في الأحاديث...",
      noHadithsFound: "لم يتم العثور على أحاديث.",
      hadithsCount: "أحاديث",
      selectBookChapter: "اختر كتابًا/فصلاً للقراءة.",
      book: "كتاب",
      section: "القسم",
      hadithsAvailable: "حديث متاح",
      grade: "الدرجة",
      reference: "المراجع",
      
      // Navigation & Actions
      next: "التالي",
      finish: "إنهاء",
      completedPrayerAdhkar: "لقد أتممت أذكار هذه الصلاة.",
      salah: "الصلاة",
      common: "العام",
      myPlan: "خطتي",
      startRoutine: "ابدأ الخطة",
      noItemsInPlan: "لا توجد عناصر في خطتك. اضغط + لإضافة ذكر.",
      hijriDate: "التاريخ الهجري",
      ramadan: "رمضان",
      ramadanDesc: "رمضان يعتمد على التقويم الهجري، لذلك تتغير تواريخه كل عام ميلادي.",
      lastTenNights: "العشر الأواخر من رمضان",
      lastTenNightsDesc: "هذه الليالي وقت مميز للقيام والقرآن والتماس ليلة القدر.",
      eidAlFitr: "عيد الفطر",
      eidAlFitrDesc: "يوم فرح وشكر مع صلاة العيد وصلة الأرحام.",
      firstTenDhulHijjah: "أول عشر أيام من ذي الحجة",
      firstTenDhulHijjahDesc: "من أفضل أيام العام للذكر والعبادة والعمل الصالح.",
      dayOfArafah: "يوم عرفة",
      dayOfArafahDesc: "يوم عظيم للدعاء والصيام لمن لم يكن في الحج.",
      eidAlAdha: "عيد الأضحى",
      eidAlAdhaDesc: "يوم العيد والصلاة والشكر وصلة الرحم.",
      islamicNewYear: "رأس السنة الهجرية",
      islamicNewYearDesc: "يبدأ العام الهجري اليوم، وهو تاريخ يتغير كل عام مقابل التقويم الميلادي.",
      dayOfAshura: "يوم عاشوراء",
      dayOfAshuraDesc: "يوم مبارك في محرم يُستحب فيه الصيام والشكر.",
      whiteDaysFasting: "صيام الأيام البيض",
      whiteDaysFastingDesc: "اليوم الثالث عشر والرابع عشر والخامس عشر من الشهر الهجري أيام يستحب صيامها.",
      tasuaFast: "صيام تاسوعاء",
      tasuaFastDesc: "صيام اليوم التاسع من محرم مع عاشوراء من السنن المباركة.",
      ramadanFastToday: "صيام رمضان اليوم",
      ramadanFastTodayDesc: "تابع صيامك يومًا بيوم خلال رمضان حتى يبقى التقدم مرتبطًا بالتقويم الهجري.",
      ramadanKhatam: "ختم القرآن في رمضان",
      ramadanKhatamDesc: "اسعَ إلى ختم القرآن كاملًا في رمضان مع تتبع تلقائي للصفحات المقروءة.",
      sixOfShawwal: "صيام ست من شوال",
      sixOfShawwalDesc: "تابع صيام الست المستحبة من شوال بعد عيد الفطر.",
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isRTL: language === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
};
